Enhanced Goals
portal-cornell/robotouille pull request #29
Opened 2024-04-15 17:16 UTC by lsuyean

## Overview

Previously, goals needed to be specified using objects declared within the problem file. This means that  goals that involved created objects were impossible (like checking if a pot has been filled up with water, a created object). In this PR, I enhance goals to be able to include goals that could achieve this. 

When specifying goals that involve created objects in the problem file, there are two ways: unique goals and combination goals. 

**1. Unique Goals - goals that require specific objects defined in the domain**
The way we define unique goals is using ids, such as "a". If our goal requires a specific object (e.g. filling pot with id "a" with water being the created object), we need to give the created object a unique new id. 

```
{
    "predicate": "in",
    "args": ["water", "bowl"],
    "ids": ["c", "b"]
}
```

**2. Combination Goals - goals that do not require specific objects defined in the domain **
When specifying goals where any object of the same name and type can be used, we use numeric ids in the goal specification (e.g. fill any pot with water being the created object). In this case, we also use the same id convention and give the water a numeric id.

```
{
    "predicate": "addedto",
    "args": ["tomato", "water"],
    "ids": [1, 2] 
}
```

## Changes Made

- Edited state.py so that goals do not need to include objects defined in domain
- Edited builder.py and env.py to create objects for goals with objects not defined in domain
- Fixed bug that wrongly created predicates for station location
- Fixed bug that allowed pot to be filled when not in sink (added a conditional sfx)

## Test Coverage

Tested manually

## Related PRs or Issues (delete if not applicable)

Closes #27

2024-04-17 17:31 UTC, chalo2000 requested changes
Leaving some temporary feedback in response to our conversation

2024-04-17 17:31 UTC, chalo2000 commented on environments/env_generator/builder.py
> +                    combination_dict[arg]['entities'] = arg_entity_names if arg_entity_names else [arg + "1"]
This will likely limit us in the future with creating multiple objects that are part of a goal

2024-04-17 17:44 UTC, lsuyean commented on backend/state.py
> +                if goal.name not in list(map(lambda x: x.name, domain.predicates)):
defined list outside of loop

2024-04-17 17:47 UTC, lsuyean commented on backend/state.py
> +        return self.predicates[predicate] if predicate in self.predicates else False
Documentation updated

2024-04-17 17:48 UTC, lsuyean commented on environments/env_generator/builder.py
> +        if environment_dict.get("items"):
updated accordingly

2024-04-17 17:49 UTC, lsuyean commented on environments/env_generator/builder.py
> +    if environment_dict.get("items"):
Updated

2024-04-22 19:22 UTC, lsuyean commented on robotouille/env.py
> +        for field in ["players", "items", "containers"]:
Separated players loop from items and containers loop for clarity

2024-04-22 19:22 UTC, lsuyean commented on robotouille/env.py
> +            match = False if field == "players" else match
Separated players loop from items and containers loop

2024-05-01 19:49 UTC, merged